### ISSUE TITLE
Loading alert (popup) have default OK button

### ISSUE THREAD

**Issue by sdgmits** [PaulNieuwelaar/alertjs#12]
How can we get rid of default OK button for a loading alert? and do NOT show any button.

It does not make sense to give 'OK' button when a process is running behind the scene and Loading alert should go automatically once behind the scene process completed.  If OK button is available, one can click on it and not wait for the response to come back,

//Show progress bar
 Alert.show("Processing", null, null, "LOADING", 250, 150, null, true, null);

![2018-03-15_11-53-16](https://user-images.githubusercontent.com/6667156/37474952-ee190b02-2847-11e8-822f-23428f460f14.png)

**Comment by sdgmits** [comment]
@PaulNieuwelaar , I think, I found a solution for this issue with a reference from your comment on another post.

If we use in below way, then OK button wouldn't come by default.

//Show progress bar
Alert.show("Processing...", null, [], "LOADING", 250, 150, null, true, null);

Thanks.

**Comment by PaulNieuwelaar** [comment]
Hi, yup as per documentation, passing an empty array is the correct way to display no buttons. You can also used the showLoading function as well.
