### ISSUE TITLE
Expand full screen button or full screen launch

### ISSUE THREAD

**Issue by iamgmd** [PaulNieuwelaar/alertjs#13]
Hi Paul,

Thanks for your hard work on Alertjs. I am launching a webresource in an Alert, is there a feature to launch full screen and/or have a button to expand to full screen? If not, wonder if this could be considered as a new feature?

Regards,

Geoff.

**Comment by PaulNieuwelaar** [comment]
Hi Geoff, this feature will be coming in V3, which is going to be released very soon! Cheers, Paul
