### ISSUE TITLE
Alert JS doesn't work on HTML Web resource

### ISSUE THREAD

**Issue by afaquezaidi** [PaulNieuwelaar/alertjs#14]
I am trying to use Alert popup on a HTML Web resource button click event. 
I have added alert.js script reference on HTML page but its always giving error "Alert is undefined". However I have checked IE developer tool alert.js file is loading.
![capture_alertjs](https://user-images.githubusercontent.com/34897737/38318069-87ad0142-37fc-11e8-8188-bdf2aacf2fb4.JPG)

**Comment by PaulNieuwelaar** [comment]
Hi, make sure the alert.js web resource is actually being loaded correctly. I see your other "Scripts" web resource only has one "../" but the alert reference has 2. If that doesn't work, try using the full URL and work your way from there. -Paul

**Comment by mobaasa** [comment]
i try to call 'showWebResource' function but doesn't work give me the error in the following image, iam already loaded the alert.js on form 
![issuee](https://user-images.githubusercontent.com/38618885/39095456-eaf20020-4640-11e8-9dcb-b2b3866f3997.png)

**Comment by PaulNieuwelaar** [comment]
Are other alert js functions working? Looks like the web resource name is incorrect. Can you show the code you're using?

**Comment by mobaasa** [comment]
OK its work fine, but there are another issue after some of time using alert to show web resource this script error view 
**"One of the scripts for this record has caused an error. For more details, download the log file.ReferenceError: 'showwebresource' is undefined at eval code (eval code:1:1)"**

**Comment by PaulNieuwelaar** [comment]
It should be "showWebResource". Can you post your code?

**Comment by mobaasa** [comment]
code was working fine but suddenly view this issue 
"showwebresource" is the name of function 
function showwebresource()
{
    var baseUrl = Xrm.Page.context.getClientUrl();
    Alert.showWebResource("new_TextboxwithLabel", 610, 300, "Enter Number of Items", [new    Alert.Button("OK", callback)], baseUrl, true, 30);
}

**Comment by PaulNieuwelaar** [comment]
Looks like the issue is with your outer function. Possibly something you're doing while calling the function?
