### ISSUE TITLE
Unable to get property '$' of undefined or null reference in IE

### ISSUE THREAD

**Issue by aqim22** [PaulNieuwelaar/alertjs#15]
I have one custom ribbon in dynamic CRM that will popup my custom HTML web resources. In my custom HTML form I use alert.show popup on a button onClick. I already add all reference but still '$' is undefined. I also use full URL for the reference still not working. I have checked IE developer tool all the reference file are loaded.

![formapproval](https://user-images.githubusercontent.com/18108496/38654459-0a9c2998-3e42-11e8-914d-3028bc0aa59e.PNG)

When I click cancel to open alert popup then getting this error

![approvalcancel](https://user-images.githubusercontent.com/18108496/38654543-6e05e384-3e42-11e8-8ea3-cb5dc50db1b7.PNG)

**Comment by PaulNieuwelaar** [comment]
Hi, it sounds like the JQuery file isn't being loaded. One of the first things that gets declared inside the alert.js file is the Alert._jQuery variable. This uses window.$ or parent.$ depending on whether jQuery is defined in the current window. If it's not defined, it tries to get parent.$, and if there is no parent of your web resource, parent will be undefined, so parent.$ will give you that error.

Couple of things to try:
Check the jQuery reference is correct. I notice there's no ".js" on the end, but this may be the actual file name. And I notice the prefix is mag_new_ but again this may be what it actually is, just might pay to double check it is correct.

Secondly, when you load ClientGlobalContext, I believe it will load in jQuery for you as well - however you're loading this in after alert.js, so the error would've already happened (this might be why it looks like jQuery is being loaded correctly). You should be able to just move the alert.js reference to be below Context, if you find your jquery reference is not the problem.

Let me know if either of those work.

-Paul
