### ISSUE TITLE
Popup dialog box useing Alert.js and ribbon workbench

### ISSUE THREAD

**Issue by alexander-you** [PaulNieuwelaar/alertjs#16]
Hi,

I created custom ribbon button using in ribbon workbench which pop-up a dialog box using Alert.js (by followeing this guide [LINK).](http://www.businessintelligenceinfo.com/crm/microsoft-dynamics-crm/how-to-display-alerts-and-dialog-processes-with-alert-js-in-dynamics-365)
now from some reason the button works only once per form load. so if the user enter the form for the first time clicks on the button he sees the pop up then he decided to close it when he click on the button next time the pop-up will not show and in order to pop up the window he needs to refresh the page.

Any ideas for why this happens?

Btw this s my code:

`Alert.showDialogProcess ("62922E82-47FE-4100-9485-7D81370935B6", "phonecall", 
Xrm.Page.data.entity.getId(), Xrm.Page.data.refresh(), 1200, 600)`

[WorkBrench](https://community.dynamics.com/cfs-file/__key/communityserver-discussions-components-files/761/_0F200F20_popuperror.PNG)

**Comment by PaulNieuwelaar** [comment]
Hi Alex, looks like it's failing because the callback function is not being added correctly. You'll need to wrap it with function() { } like in the documentation example. As it is currently the refresh will occur before the dialog is displayed, which will likely mess up the alerts. Let me know if that works. Paul

**Comment by alexander-you** [comment]
Hi @PaulNieuwelaar 

Thanks for your replay. 

I'm not sure I did it right (I'm new to JS and only studying) - Anyway, unfortunately it did not work :(

`Alert.showDialogProcess  ("62922E82-47FE-4100-9485-7D81370935B6", "phonecall", Xrm.Page.data.entity.getId(),  function() { Xrm.Page.data.refresh (); }, 1200, 600)`

**Comment by PaulNieuwelaar** [comment]
Hi Alex,

That looks correct now. However, looking at your ribbon workbench screenshot, you've got the function name as "alert.showDialogProcess", which doesn't look quite right. Is this the name of your function in your web resource? Can you show more context of your web resource, i.e. the function definition?

Ideally, the outer function should use your own namespace (not "alert"), or the function should just be something like "showDialogProcess" without the alert namespace. Then inside your custom function, you make the call to Alert.showDialogProcess as you've shown.

Hope that helps.
Paul

**Comment by PaulNieuwelaar** [comment]
Hi Alex,

Did you manage to solve this?

Cheers,
Paul
