### ISSUE TITLE
question before buying the third version

### ISSUE THREAD

**Issue by alexander-you** [PaulNieuwelaar/alertjs#18]
Hello,

I would like to popup a window with two questions and a button. On button click I would like to pass the answers to an action and execute it.

so I created an action with 3 arguments: two arguments are my questions from type Boolean and third is an output argument: [Action Test](https://community.dynamics.com/cfs-file/__key/communityserver-discussions-components-files/762/Capture3323.PNG)

from this point I'm a little bit clueless of what I need to do. basically I want to popup a window [like this one](https://community.dynamics.com/resized-image/__size/520x420/__key/communityserver-discussions-components-files/762/_0F200F20_123.PNG) with two Boolean questions and button which will pass the answers to the action and will execute the action. 

is that something that I can do with the third version of alertjs? From what I understand I can't  do it with the current version of alertjs?

Thanks @PaulNieuwelaar

**Comment by PaulNieuwelaar** [comment]
Hi Alex,

You can certainly do this with Alert.js version 3.0. You could either display the options as a list (drop down), a set of radio buttons, or simply a checkbox. The response values are passed to the button callback, which you can then pass into your action.

If you'd like to trial Alert.js v3.0 before you buy it, to make sure it works the way you're expecting, you can [contact us](https://www.magnetismsolutions.com/contact-us) and we'll sort you out. I can also help you get the code working the way you want, if you have any issues/questions setting it up.

Cheers,
Paul

**Comment by alexander-you** [comment]
Just send the contact us form.
Thanks.



בתאריך יום ו׳, 8 ביוני 2018, 14:43, מאת Paul Nieuwelaar ‏<
notifications@github.com>:

**Comment by PaulNieuwelaar** [comment]
Sweet, you should get a response on Monday, if not earlier, with the trial solution. 

You've probably already found the documentation, but just in case, here's the section about showing prompts: https://github.com/PaulNieuwelaar/alertjs/wiki/Documentation-v3.0#showprompt. See the example at the bottom of that section for how the button callback accesses the responses.

Let me know if you have any questions.

Cheers,
Paul

**Comment by PaulNieuwelaar** [comment]
Hi Alex,

Did you get a response to your contact us request? If not, can you please email me directly and I'll get you sorted with the trial: [email redacted]
Cheers,
Paul
