### ISSUE TITLE
Alert.showWebResource -404 ERROR

### ISSUE THREAD

**Issue by alexander-you** [PaulNieuwelaar/alertjs#19]
Hello

I'm trying to popup a web resource HTML page using Alert.showWebResource method.
this is my code:
`Alert.showWebResource("new_A_TEST.html", 800, 800, "test", [new Alert.Button("OK", doSomething)], , true, 30)`

unfortunately song from some reason I'm getting 404 error: https://imgur.com/a/5Q8o7xB

Can some help me :(

**Comment by PaulNieuwelaar** [comment]
Hi Alex,

I noticed your baseUrl is not being set. I'm assuming you've cut this out of your code snippet before posting it here. My best guess is that the baseUrl is wrong, which is causing the web resource URL to not resolve correctly. If you're running this from a form or view, you can set the baseUrl to null, and it will automatically resolve.

Let me know if that works.

Cheers,
Paul
