### ISSUE TITLE
Has this been tested using CRM 9 Update. seems alert.js is not working correctly 

### ISSUE THREAD

**Issue by ghost** [PaulNieuwelaar/alertjs#2]
Loading doesnt seems to work ? - any ideas 

Thanks in advance

**Comment by PaulNieuwelaar** [comment]
Hi, yup this has been tested with v9 and everything still works, including showLoading. Can you share your exact code? And have you loaded the Alert.js web resource?

**Comment by PaulNieuwelaar** [comment]
Hi, Haven't heard back from you so I'm going to assume you've managed to solve this now. Please feel free to to reply again if need any further assistance. Cheers, Paul
