### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by r-weisser** [PaulNieuwelaar/alertjs#20]
Hi,
I'm using latest Source 2.1 with Dynamics 365. 
I created a custom ribbon and added alert.js and my functional-javascript into actions area.

After watching the popup, it fails handling the button clicks on Line:208
```csharp 
Alert.$(".alert-js-RefreshDialog-Button").prop("disabled", true);
```
with error message:
VM4276:208 Uncaught TypeError: Alert.$(...).prop is not a function
    at Function.Alert._buttonClicked (<anonymous>:208:47)
    at HTMLButtonElement.<anonymous> (<anonymous>:151:23)
    at HTMLButtonElement.handle (jquery1.4.1.min.js:69)
    at HTMLButtonElement.j (jquery1.4.1.min.js:64)

Whats wrong here?

EDIT: just read that jquery 1.6 is required for ```prop()```-Method. So how is this supposed to work since jQuery1.4.1 is default in crm ?

**Comment by PaulNieuwelaar** [comment]
Hi, I'm looking at Dynamics 365 online (8.2), and the jQuery version is 2.1.1. Even in CRM 2013 onprem (which Alert.js supports) the jQuery version is 1.7.2. Are you by any chance loading a different version of jQuery onto the form manually?
