### ISSUE TITLE
Unable to call  a function inside a webresource from OK button

### ISSUE THREAD

**Issue by crmprocorp** [PaulNieuwelaar/alertjs#21]
Unable to call  a function inside a webresource from OK button. I am using the following
var iFrameWindow = Alert.getIFrameWindow();
iFrameWindow.document.**UploadExcel**(); 

Where UploadExcel is my webresource js function.

Bhaskar

**Comment by PaulNieuwelaar** [comment]
Hi Bhaskar,

The function will be against the iFrameWindow, rather than the iFrameWindow.document.

Try just: `iFrameWindow.UploadExcel();`

Hope that helps,
Paul
