### ISSUE TITLE
Use alert.showwebresource to get message from user

### ISSUE THREAD

**Issue by payamiii** [PaulNieuwelaar/alertjs#22]
hi. i used alert.js version 2.1 in my organization. i want to use alert.showwebresource to show a multiple line text box to user and user can add a message and after that click on OK button and i set that message in my form or fire a workflow. please help me to create HTML web resource for this situation .

**Comment by PaulNieuwelaar** [comment]
Hi, this is possible with v2.1 if you create your own web resourse and logic, however version 3 does this a lot easier, you may be interested in checking out the v3 documentation around showPrompt to see if that will work for you. Let us know if you want a trial of v3, and we can send it to you.

**Comment by payamiii** [comment]
hi Paul. i sent my request to have your v3 alert.js but i didn't see any response from magnetism until now.
can you send v3 for me? 
and if you can not please help me to create correct HTML web resource for my problem.

**Comment by PaulNieuwelaar** [comment]
Hi, what email address did you put on the contact form? I'll follow up with our sales team to see if it came through, and if not we'll send it again. We're only providing limited support for v2.1 now. Cheers, Paul

**Comment by payamiii** [comment]
I put [redacted]@hotmail.com on the contact form. thanks paul for your following up

**Comment by PaulNieuwelaar** [comment]
Hi, did you end up receiving the v3 trial, and were you able to achieve what you were trying to do? Cheers, Paul

**Comment by payamiii** [comment]
Hi dear Paul, Unfortunately i didn't catch any respond from the sales team about trial version.  i don't know what to do about this!!!

**Comment by PaulNieuwelaar** [comment]
Hi, do you have a work email rather than hotmail?

**Comment by PaulNieuwelaar** [comment]
Hi, just letting you know the v3.0 trial can now be downloaded from here, if you're still interested: https://github.com/PaulNieuwelaar/alertjs/releases/tag/v3.0

**Comment by payamiii** [comment]
hi dear Paul, yes my other work email is [redacted], and i am so interested to use version 3. i download file from link that you typed above. thanks for your helps.
