### ISSUE TITLE
Alert.showWebResource custom button closing alert

### ISSUE THREAD

**Issue by mikejramsey** [PaulNieuwelaar/alertjs#26]
I'm using version 2.1. 

I have a quote form with a custom ribbon button that calls Alert.showWebResource and loads a custom html resource with an ExtJs ViewPort and backing viewmodel.js... this all works perfectly fine. the viewport has a custom OK and Cancel button. What i cannot figure out is how do I simply close the Alert from the Cancel button callback, and close the alert in the success of the OK callback. 

I've tried simply calling Alert.hide() in the cancel callback, but that doesn't "do" anything. the Alert is still displaying. I've tried getting the window with Alert.getIFrameWindow, and Alert.getCrmWindow, neither lets me actually hide the Alert itself. 

Thanks in advance, 
Mike

**Comment by mikejramsey** [comment]
Stepping into the call for Alert.hide() and it is calling the hide function, however Alert._initialised is false. 
I can of course cheat and just call Alert.$("#alertJs-wrapper").hide(); in the cancel callback function, but that seems a little wrong to me. I'm curious as to why the _initialised is false in Alert.showWebResource??

![image](https://user-images.githubusercontent.com/893811/49204525-2ceba300-f37a-11e8-8871-c9fd4ea253d9.png)


![image](https://user-images.githubusercontent.com/893811/49204480-0c234d80-f37a-11e8-9946-3e781ff6a73a.png)

**Comment by ramakanta090** [comment]
@mikejramsey  i am also trying use Alert.hide(); function to close my loading message( **Alert.showLoading();**) but its not working...I have also tried your approach but no luck

**Comment by clemfernandez** [comment]
I use `parent.Alert.hide()` from the Web resource and it does work fine.

However, both the default X and my custom Cancel button won't work on MS Edge, while they work fine on Chrome and Firefox.

**Comment by PaulNieuwelaar** [comment]
Hi Mike,

It looks like the alert.js web resource might be getting loaded multiple times, so the global variables are being reset. This would only really be an issue if an alert is displayed BEFORE the second web resource is loaded. Can you check if there are any other instances of the web resource being loaded?

Cheers
Paul
