### ISSUE TITLE
Dynamics CRM 365 (v9) compatibility

### ISSUE THREAD

**Issue by MMlinsek** [PaulNieuwelaar/alertjs#28]
Hello,

I have one quick question. Is this library compatible with latest version of Dynamics CRM 365 (v9)?

Thank you in advance. 

Best Regards,

Matej

**Comment by PaulNieuwelaar** [comment]
Hi Matej,

Yes Alert.js is fully compatible with the latest version of Dynamics 365 v9+ and is constantly updated to keep up with the latest CRM releases.

You can download the free trial version and test this in your environment to ensure it's all working correctly for you. If you do notice any styling issues etc, you can create an issue and we'll get that resolved as soon as possible.

Cheers,
Paul

**Comment by MMlinsek** [comment]
Thank you for your fast response. Is it possible to get
Xrm.Page.data.entity from parent crm form after opening webresource using
your library?

Usually I get Xrm Page using parent.Xrm.Page, but data.entity attribute is
undefined. Thank you in advance.

Best regards,

Matej



V V čet., 26. sep. 2019 ob 00:46 je oseba Paul Nieuwelaar <
notifications@github.com> napisala:

**Comment by PaulNieuwelaar** [comment]
Hi Matej,

Yes it's possible to access the form functions from inside the web resource. For this you should be using the getCrmWindow function. Documentation/usage for both versions below (depending on what version you're using).

v2.1: https://github.com/PaulNieuwelaar/alertjs/wiki/Documentation#alertgetcrmwindow
v3.0: https://github.com/PaulNieuwelaar/alertjs/wiki/Documentation-v3.0#getcrmwindow

In your case, once you've got the window, you can access Xrm.Page etc from there.

E.g. parent.Alert.getCrmWindow().Xrm.Page.

**Comment by MMlinsek** [comment]
OK, thank you.

Have a nice day.

Best regards,

Matej

V V tor., 1. okt. 2019 ob 04:30 je oseba Paul Nieuwelaar <
notifications@github.com> napisala:

**Comment by MMlinsek** [comment]
Hello, we're testing your library and we have some problems with catching
on close/hide event of webresource window. Is it possible to execute some
code on Alert.hide() event? Thank you. Best Regards, Matej

V tor., 1. okt. 2019 10:56 je oseba Matej Mlinsek <matejm@gmail.com>
napisala:

**Comment by PaulNieuwelaar** [comment]
Hi, in this case you'd need to prevent closing the alert via the default 'X', so you can control the callback function yourself.

https://github.com/PaulNieuwelaar/alertjs/wiki/Documentation-v3.0#base-alert-object
Set 'preventCancel' to true to remove the default 'X' button which hides the alert, then add your own custom button to handle your logic + hide the alert.

Cheers,
Paul

**Comment by MMlinsek** [comment]
Ok, thank you.

Best regards,

Matej

V sob., 19. okt. 2019 08:07 je oseba Paul Nieuwelaar <
notifications@github.com> napisala:
