### ISSUE TITLE
Dynamics 365 8.2 and Mobile App?

### ISSUE THREAD

**Issue by CHTEEVE** [PaulNieuwelaar/alertjs#3]
Is someone tested it with the mobile App? It would probably not working as expected?

Thanks!

Steeve G.

**Comment by PaulNieuwelaar** [comment]
This has been tested with everything up to v9. Mobile I haven't tested with the latest versions, but it was working with CRM 2016 when I last tested. It might look weird on smaller screens, but it should work.
