### ISSUE TITLE
Issue using input fields on UI on Android devices in "portrait mode"

### ISSUE THREAD

**Issue by simoneboniolo** [PaulNieuwelaar/alertjs#30]
We are using the free version of Alert.js v2.1 in order to open modal web-resources in D365 v9 (Unified Interface).
We found an issue using it on Android devices in "portrait mode" (both using the browser or the D365 app).
The specific issue occurs when the user clicks on an input field: the keyboard appears and after less than 1 second automatically disappears.
We verify that the keyboard disappearing is caused by a change focus event.
We tested it putting in the alert a simple HTML having only one input field with no JSs or additional code, and the issue occurs in the same way.
Have you got any suggestion on how to solve it?
Thank you.
Best regards.
Simone

**Comment by PaulNieuwelaar** [comment]
I've tested this with v3.1 using the showPrompt method and the android keyboard appears correctly. I'd recommend trying the [v3 trial](https://github.com/PaulNieuwelaar/alertjs/releases/download/v3.1/AlertJS_3_1_1_managed.zip) as it's specfically built to support inputs, unlike v2.1.
