### ISSUE TITLE
Xrm.Page / formContext

### ISSUE THREAD

**Issue by vernetmatias** [PaulNieuwelaar/alertjs#31]
Hello Paul, I am updating all javascripts from the Dynamics, that uses Xrm.Page to the formContext. I am not a specialist on javascript and I would need a bit of help. I need to understand if you are going to release a new version with de code updated with the formContext or if you could help me to update the one Im using version, alert.js v2.1. Thanks!!

**Comment by PaulNieuwelaar** [comment]
Hi, the next release of v3 will include changes to support the new Xrm methods for CRM online. v2 will not be updated with these changes. Cheers
