### ISSUE TITLE
Theme colors

### ISSUE THREAD

**Issue by fvakiliev** [PaulNieuwelaar/alertjs#32]
Hi Paul!

Does the solution v3.1 support **Dynamics 365 Themes** (colors)? All my buttons are blue. ;)

Thanks,
OldCat

**Comment by PaulNieuwelaar** [comment]
Hi, yes in v3.1.x the buttons and dialog title are coloured using the system theme main colour by default, unless otherwise specificed.

> * New color option to set the title and button color. Accepts valid CSS 'color' values, e.g. "#FF6A00", "rgb(0,0,0)", or "red" (but hex recommended for hover effect on primary buttons).
>    * Color defaults to using the CRM theme's main color (unless explicitly set).

**Comment by fvakiliev** [comment]
Tested. Thanks!
This Issue must be closed.
