### ISSUE TITLE
Change font-size issue

### ISSUE THREAD

**Issue by fvakiliev** [PaulNieuwelaar/alertjs#34]
Hi Paul!

How I can change default font size from 11px to 14px? But 11 it's too small.
Why I can't change **mag_/css/alert.css** webresource ?

Thanks,
OldCat

**Comment by fvakiliev** [comment]
Any news?

**Comment by PaulNieuwelaar** [comment]
Hi, the font sizes are set to match the default styles that CRM uses for fields and popups etc. Which text specificity are you looking to change? You can possibly inject your own styles into each dialog or modify the base css file, however this could become out of sync with updates.
