### ISSUE TITLE
Alert js is not working on HTML web resource 

### ISSUE THREAD

**Issue by kyilintun2017** [PaulNieuwelaar/alertjs#36]
Hi Paul, 
             I try to use alert.show and Dialog(option).showLoading() function in my html web resource Iframe in D365 CRM.  
             I can call the function from my html webresource. But the loading message doesn't appear.
             I try to debug there's no error.
           
             alert.js version - 3.1.1

         Edit: the scripts were working fine on Ribbon workbench and CRM form.

**Comment by kyilintun2017** [comment]
![image](https://user-images.githubusercontent.com/26317504/129589986-25fb03f0-f8d1-4c20-8e6e-df2bbe1ed2a5.png)

var _options = { id: "loading", 
                                     title: "Processing..." ,
                                     buttons : [],
                                     preventCancel : true,
                                     width : 500,
                                     height : 120,
                                     baseUrl :   parent.Xrm.Page.context.getClientUrl() 
                                    };
new Dialog(_options).showLoading();

the steps go smoothly but no error was given and also nothing shows up.

![image](https://user-images.githubusercontent.com/26317504/129590989-64d3283c-576f-4e4f-93dc-759b12c215c9.png)

**Comment by PaulNieuwelaar** [comment]
Hey, when using it in web resources you should include a reference the to alert.css file, just like you're doing to reference the alert.js file.

You can also add a reference to the Xrm global context so you don't need to set the baseUrl.
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/getglobalcontext-clientglobalcontext.js.aspx

**Comment by kyilintun2017** [comment]
Hi Paul,
            Its work I didn't aware about alert.css file thank you.
