### ISSUE TITLE
New Look and Lookups inside dialogs.

### ISSUE THREAD

**Issue by sebgauthier** [PaulNieuwelaar/alertjs#37]
When the "New Look" (https://learn.microsoft.com/en-us/power-apps/user/modern-fluent-design) css is turned on, lookup inside dialogs are disabled. Reverting back to the old theme fixes the issue.

![image](https://github.com/PaulNieuwelaar/alertjs/assets/44874281/b36474c0-c5fd-4e45-9cd5-eb26bd60ab25)

**Comment by PaulNieuwelaar** [comment]
Hi Seb, a bit late replying to you sorry, but this should be fixed with v3.3.5.
