### ISSUE TITLE
Trigger on view or dashboard page load

### ISSUE THREAD

**Issue by forceworks** [PaulNieuwelaar/alertjs#5]
Is there a way to trigger an alert on the onload of a Dashboard or View page?

**Comment by forceworks** [comment]
Sorry, in Dynamics 365

**Comment by PaulNieuwelaar** [comment]
Yup, just add a command bar button to the grid view, then execute your alert logic in the enable rule. The button can be always hidden as a result of the enable rule, as long as your logic executes first.

**Comment by forceworks** [comment]
Thanks Paul, awesome little tool BTW
