### ISSUE TITLE
Validation Issue

### ISSUE THREAD

**Issue by forceworks** [PaulNieuwelaar/alertjs#7]
Hi Paul,

It seems with V9, alert.js is failing on these unsupported items:

JavaScript   - Do not assume that the parent window is the Microsoft Dynamics 365/CRM form | High | ..\WebResources\h2_\js | alert.js | 26
JavaScript - Do not assume   that the parent window is the Microsoft Dynamics 365/CRM form | High | ..\WebResources\h2_\js | alert.js | 55
JavaScript - Do not assume   that the parent window is the Microsoft Dynamics 365/CRM form | High | ..\WebResources\h2_\js | alert.js | 59

Is this something you are aware of?

**Comment by PaulNieuwelaar** [comment]
Hi, I've just tested some of the functions again on V9, in particular the getCrmWindow and getIFrameWindow and they both seem to be returning the correct objects for me. Could you share the code snippet you're using to display the alert? And if you're displaying a web resource, could you share any code that references back to the Alert.js library? Also, at what point does the error occur? Cheers, Paul

**Comment by forceworks** [comment]
Thanks for replying Paul,

The functionality works. The issue is that Microsoft treats window.parent, document.parent and parent.$ as unsupported code from version 9 on.

Thanks!

Steve Mordue
813-263-7129

**Comment by PaulNieuwelaar** [comment]
Ah yup, in this case it's only using window.parent to get access to jQuery, and it handles both scenarios of turbo forms on/off. It also appends the alert wrapper directly to the top frame, so it doesn't matter about the form context etc, it will work regardless. This library is still technically unsupported as it manipulates the DOM, but it's done in a way that has very low dependencies on anything CRM, so it "should" continue to work going forward. Cheers for the feedback 😃 - Paul

**Comment by amervitz** [comment]
A ramification of the unsupported techniques used is Microsoft isn’t allowing submissions to AppSource with this library included as a dependency. I’d suggest this caveat be disclosed in the readme.

**Comment by PaulNieuwelaar** [comment]
Hi Alan, I'm pleased to announce that Alert.js v2.1 has now been approved for App Source, so you should have no problems listing this as a dependency now 😃- Paul

**Comment by amervitz** [comment]
@PaulNieuwelaar that's great news. Were there any changes required (and which commit has the changes?) or are the AppSource certification team now allowing the techniques that are taken? It would be very helpful to reference something if this gets flagged in the future during certification.

**Comment by PaulNieuwelaar** [comment]
No changes required, so it's just the current version 2.1. Things like "parent." will still get flagged by the automated verification process, but you should be able to reference the Alert.js app source page to show that it's already been approved.
