### ISSUE TITLE
Nested Alerts

### ISSUE THREAD

**Issue by Sheeley7** [PaulNieuwelaar/alertjs#9]
More a feature/question: Is there a way I can nest these alerts? I'd love to put a custom wizard in the iframe alert and have confirmation alerts within that iframe. Currently, if I try to add another alert, it closes out the original iframe.

**Comment by PaulNieuwelaar** [comment]
Hi, 

Unfortunately there's currently no way to show multiple alerts at the same time. The workaround is usually to just show standard browser alerts, confirms, and prompts etc when needing to do confirmations inside an alert.js popup. However, as this is a commonly requested feature, it will be considered in future releases.

Thanks for the feedback,
Paul
